### ISSUE TITLE
Issue 1: User can log workout

### ISSUE THREAD

**Issue by marvinloreto** [marvinloreto/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log the workout and exercises they've done for the day.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users click 'Start Workout', a form is rendered where users can enter their exercise information and click 'Log Exercise' to add the exercise for the day.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (304)](https://user-images.githubusercontent.com/117399643/220710653-a91a8ca8-0c59-4e53-a221-e8ecf027e265.png)

![Screenshot (305)](https://user-images.githubusercontent.com/117399643/220710920-d646bac8-1ccc-456e-8f61-0d1218d68831.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create database 'workoutTracker'
- [x] Get schema.sql updated and copied into code
- [x] Update `data.sql` with dummy data

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Destructure name, sets, reps, and notes from req.body object
 - [x] Check to see if required entries are given, if not throw client error.
 - [x] Add sql to add values to database
 - [x] Create param variables for sql code
- [x] Query the database
- [x] Add callback function with param results and destructure entries from result.rows
- [x] Catch all potential errors. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create component to handle hash routing and page state.
- [x] Create an exercise entry form component page
- [x] Add css

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
